name: beta build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - monkey
    tags-ignore:
      # 发 release 时不触发构建
      - v*
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'
      # 暂时忽略 desktop 端的改动
      - 'apps/desktop/**'
      - packages/database

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Deps
        run: pnpm install

      - name: build and zip
        run: pnpm release

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: server/go.sum

      - name: Build Go binaries
        run: |
          cd server
          chmod +x build.sh
          ./build.sh

      - name: upload monkey
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver.user.js
          path: dist/weibo-archiver.user.js

      - name: upload web
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-webapp
          path: dist/weibo-archiver-webapp.zip

      - name: upload cli
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-cli
          path: dist/weibo-archiver-cli.zip

      - name: upload go binaries
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-binaries
          path: |
            server/dist/weibo-archiver-windows-amd64.zip
            server/dist/weibo-archiver-linux-amd64.tar.gz
            server/dist/weibo-archiver-darwin-amd64.tar.gz
