name: Beta Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - monkey
    tags-ignore:
      - '**'
    paths:
      - '!**.md'
      - '!.github/**'
      - '.github/workflows/**'

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Node.js Dependencies
        run: pnpm install

      - name: Build and Zip Frontend
        run: pnpm release

      - name: Upload Monkey Script Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver.user.js
          path: dist/weibo-archiver.user.js

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-cli
          path: dist/weibo-archiver-cli.zip

  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: server/go.sum

      - name: Install Go Dependencies and Build
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          cd server
          chmod +x build.sh
          ./build.sh

      - name: Upload Go Binaries (Windows) Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-windows-amd64.zip
          path: server/dist/weibo-archiver-windows-amd64.zip

      - name: Upload Go Binaries (Linux) Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-linux-amd64.tar.gz
          path: server/dist/weibo-archiver-linux-amd64.tar.gz

      - name: Upload Go Binaries (macOS) Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weibo-archiver-macos-amd64.tar.gz
          path: server/dist/weibo-archiver-darwin-amd64.tar.gz
